openapi: 3.0.0
info:
  title: Hannas test repo new name
  description: A description of my repo
  version: 1.0.0
  x-cortex-git:
    github:
      repository: hannavigil-test-org/hannas-test-repo
  x-cortex-tag: hannas-test-repo
  x-cortex-link:
  - url: https://github.com/hannavigil-test-org/hannas-test-repo
    name: Github Repository
    type: documentation
  x-cortex-owners:
  - type: EMAIL
    email: hanna.vigil@cortex.io
